#!/bin/bash
msg=$1
#pwd | tr 'a-z' 'A-Z'
. lib-git
#echo -e "\033[0;34;48m sss \033[m"
echo -e "BRANCH: $green$(current_branch)$norm"

savepath=`pwd`
rootpath=`git rev-parse --show-toplevel`
cd "$rootpath"
git add -A .
if [[ "$msg" == "" ]]; then
	[[ "$GITHOST" == "" ]] && echo "\$GITHOST not defined!" && cd "$savepath" && exit
	msg="$(echo $GITHOST)-up"
  fi
git commit -m "$msg" # $(date +'%d.%m.%y_%k:%M')
cd "$savepath"

#gilf 1
# exit
