#!/bin/bash
. lib-git
savepath=`pwd`
rootpath=`git rev-parse --show-toplevel`
cd "$rootpath"
echo -e "BRANCH: $green$(current_branch)$norm"
files="$1"
[[ "$files" == "" ]] && git add -A .
[[ "$files" != "" ]] && git add "$files"
cd "$savepath"


