#!/bin/bash
if [[ "$1" == "" ]]; then
	git branch -lvv
	#git for-each-ref --format='%(refname:short) <- %(upstream:short)' refs/heads
	#git for-each-ref --format=$'\n'' '' '' '' '' '' ''/%(refname:short);%(upstream:short)' refs/heads | tr ';' $'\n'
	#git rev-parse --symbolic-full-name --abbrev-ref master@{u}
  else
  	gib $1
  fi

