#!/bin/bash
#git log --graph -n 20 --full-history --all --date=iso --color --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s $blue(%an - %ad%x08%x08%x08%x08%x08%x08%x08%x08%x08)%Creset"
if [[ "$1" == "" ]];then
	commits_num=20
  else
  	commits_num=$1
  fi
red="%x1b[31m"
green="x1b[32m"
norm="%x1b[0m"
blue="%x1b[33m%x1b[34m%x1b[40m"
#git log --graph -n 20 --full-history --all --date=iso --color --pretty=format:"$red%h$green%d %x09% %s $blue(%an - %ad%x08%x08%x08%x08%x08%x08%x08%x08%x08)%Creset"
git log --graph -n $commits_num --full-history --all --date=iso --color --pretty=format:"%C(red)%h%x09%C(green)%d%C(reset)%x20%C(yellow)%s$blue (%ad%x08%x08%x08%x08%x08%x08%x08%x08%x08 - %an)%Creset"


#git log -n 20 --oneline --abbrev-commit --all --graph --pretty=format:"%C(yellow)%h%x09%Creset%x09%x09%s (%an)" $*
#git log -last --pretty=format:"%C(yellow)%h%x09%Creset%an%x09%x09%s" --decorate -20 --graph $*