#!/bin/bash
if [[ "$1" == "" ]];then
	commits_num=10
  else
  	commits_num=$1
  fi
echo "ADDED   DELETED"

git log -n $commits_num -last --pretty=format:"%h%x09%Creset%an%x09%x09%s" --decorate --numstat | grep -v "^$"  | grep -vE "^[0-9a-f]{7}" | grep -vE "^-"

#git log --numstat --pretty --oneline 0f5d22e..HEAD -- <filename>