#!/bin/bash
. lib-git
source_branch=$(find_branch "$1") #; echo branch: $branch
exitcode=$?
[ $exitcode -ne 0 ] && echo not found && exit

currbranch=$(current_branch)
echo "from '$source_branch' to '$currbranch'"

echo "Pull '$source_branch'"
#git checkout $branch
gib $source_branch || exit
gul || exit

#git checkout $source_branch
gib $currbranch || (echo "FAIL! ANOTHER BRANCH !!" && exit)

#echo exitcode: $exitcode
#echo current_branch: $(current_branch)
#[ $exitcode -eq 1 ] && echo "Find branch by $1*: AMBIGUOUS" && exit
#[ $exitcode -eq 2 ] && echo "Find branch by *$1*: NOT FOUND" && exit
#[ $exitcode -eq 3 ] && echo "Find branch by *$1*: AMBIGUOUS" && exit

git merge $source_branch
#echo done