#!/bin/bash
. lib-git
currbranch=$(current_branch)
echo currbranch: $currbranch
tobranch=$(find_branch "$1")
  # [ $? -eq 0 ] 
if [[ "$tobranch" != "" ]]; then
	git checkout $branch
	  [ $? -ne 0 ] && exit
	git merge $currbranch
	  [ $? -ne 0 ] && exit
	git checkout $currbranch
	gil 7
  fi
