#!/bin/bash
# rename current remote
. lib-git
[[ "$1" == "" ]] && echo "[RENAME REMOTE] New name is missed !" && exit
#remotes=$(ls -1)
curr_remote=`current_remote`
# echo curr_remote: $curr_remote
if [[ "$curr_remote" != "" ]]; then
	git remote rename $curr_remote "$1"
  else
	remotes=$(git remote show)
	#echo remotes: $remotes
	remotes_cnt=$(echo -e "$remotes" | wc -l)
	#echo remotes_cnt: $remotes_cnt
	if [[ $remotes_cnt -eq 1 ]]; then
		git remote rename $remotes "$1"
	  else
	  	echo remote not defined
	  fi
  fi