#!/bin/bash
#git remote -v
. lib-git
curr_remote=$(current_remote)
remotes=$(git remote show)
#echo remotes: $remotes
for name in $remotes; do 
	if [[ "$name" == "$curr_remote" ]]; then
		echo -e "${red}$name$norm"
	  else
	  	echo $name
	  fi
  done