#!/usr/bin/bash
echo "Use syntax: . sw-git"
[[ "$APPS" = "" ]] && echo "\$APPS is not defined; setup it (ex. in ~/.bash_profile or by 'varadd APPS <path>') and reopen shell" && exit 1

if [ -d "$APPS/Git2.4.6" ]; then
	echo "set default git to 2.4.6"
	cmd //c "move %APPS%/Git %APPS%/Git1.9.5 && move %APPS%/Git2.4.6 %APPS%/Git"
  else
	if [ -d "$APPS/Git1.9.5" ]; then
		echo "set default git to 1.9.5"
		cmd //c "move %APPS%/Git %APPS%/Git2.4.6 && move %APPS%/Git1.9.5 %APPS%/Git"
	  fi
  fi
exit