#!/bin/bash
#pwd | tr 'a-z' 'A-Z'
. lib-git
curr_remote=$(current_remote)
echo curr_remote: $curr_remote
if [[ "$curr_remote" == "" ]]; then 
	curr_remote=$(girs)
	cn=$[$(echo "$curr_remote" | wc -l)]
	[[ $cn -ne 1 ]] && curr_remote=""
  fi
[[ "$curr_remote" == "" ]] && echo -e "${red}current remote NOT FOUND$norm" 1>&2 && exit
curr_branch=$(current_branch) #; echo curr_branch: -$curr_branch-
echo -e "${red}git pull $curr_remote $curr_branch$norm"  #-u
git pull $curr_remote $curr_branch #--all 
