#!/bin/bash
. lib-git
curr_remote=$(current_remote)
#echo curr_remote: $curr_remote
if [[ "$curr_remote" == "" ]]; then 
	curr_remote=$(girs)
	cn=$[$(echo "$curr_remote" | wc -l)]
	[[ $cn -ne 1 ]] && curr_remote=""
  fi
[[ "$curr_remote" == "" ]] && echo -e "${red}current remote NOT FOUND$norm" 1>&2 && exit
curr_branch=$(current_branch) #; echo curr_branch: -$curr_branch-
echo -e "${red}git push $curr_remote $curr_branch$norm"  #-u
#curr_remote=$(echo "$curr_remote"| perl -pe 's/\\033\[\d*(;\d*)*m//g')
#echo curr_remote: $curr_remote
#echo curr_branch: $curr_branch
git push "$curr_remote" "$curr_branch" # -u #all --all
